### ISSUE TITLE
Error about transition

### ISSUE THREAD

**Issue by nhtnguyen119** [tenaspace/react-headless-accordion#2]
#  Bug report
## Describe the bug
The slide up/down effect is not smooth when I run an accordion while another is running.
## Version
1.0.0
## Steps to reproduce the behavior
1. Open an accordion (1)
2. Open another accordion while accordion (1) is opening
## Expected behavior
The slide up/down effect is smooth in all of cases

**Comment by tenaspace** [comment]
Thanks for your report. I'm working on it. It will be fixed and released in the next version.
